// Generated by CoffeeScript 1.12.4
(function() {
  var crypto;

  crypto = require('crypto');

  module.exports = {
    calcHmac: function(data, key) {
      var hmac;
      hmac = crypto.createHmac('sha256', key);
      hmac.update(data);
      return hmac.digest();
    },
    calcMd5: function(data){
      var hash;
      hash = crypto.createHash("md5");  
      hash.update(data);  
      var encode = hash.digest('hex');  
      console.log(encode);
      return encode;  
    }
  };

}).call(this);
